name: projectarcana-aosp
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Environment..
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        command: |
          msg() {
            echo -e "\e[1;32m$*\e[0m"
          }
          my_dir="$(pwd)"
          cd $my_dir
          rm -rf arcana.sh
          wget https://raw.githubusercontent.com/NFS86/Rom-Builder/master/arcana.sh
          echo ===========================================
          msg             Linux versions.
          echo ===========================================
          cat /etc/os*
          echo ===========================================
          echo
          echo
          echo
          echo ===========================================
          msg            Check user active.
          echo ===========================================
          w
          echo ===========================================
          echo
          echo
          echo
          echo ===========================================
          msg               Disk available.
          echo ===========================================
          lsblk && df -h
          echo ===========================================
          curl -s -X POST "https://api.telegram.org/bot${tg_token}/sendMessage" -d chat_id="${tg_id}" -d "disable_web_page_preview=true" -d "parse_mode=html" -d text="<code>Hello.</code>"

    - name: Sync Rom
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        command: |
          my_dir="$(pwd)"
          rom_name="$(grep init $my_dir/arcana.sh -m 1 | cut -d / -f 4)"
          command="$(head $my_dir/arcana.sh -n $(expr $(grep '# build rom' $my_dir/arcana.sh -n | cut -f1 -d:) - 1))"
          mkdir -p $my_dir/$rom_name
          cd $my_dir/$rom_name
          rm -rf .repo/local_manifests
          bash -c "$command" || true

    - name: Building Rom
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        command: |
          my_dir="$(pwd)"
          rom_name="$(grep init $my_dir/arcana.sh -m 1 | cut -d / -f 4)"
          device=$(grep unch $my_dir/arcana.sh -m 1 | cut -d ' ' -f 2 | cut -d _ -f 2 | cut -d - -f 1)
          command="$(tail $my_dir/arcana.sh -n +$(expr $(grep 'build/envsetup.sh' $my_dir/arcana.sh -n | cut -f1 -d:) - 1)| head -n -1 | grep -v '# end')"
          cd $my_dir/$rom_name
          export CCACHE_EXEC=/usr/bin/ccache
          export USE_CCACHE=1
          export ALLOW_MISSING_DEPENDENCIES=true
          ccache -o compression=true
          ccache -o compression_level=1
          ccache -o limit_multiple=1
          ccache -o max_size=150G
          ccache -z
          bash -c "$command"

    - name: Push Rom
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        command: |
          my_dir="$(pwd)"
          rom_name="$(grep init $my_dir/arcana.sh -m 1 | cut -d / -f 4)"
          device="$(grep unch $my_dir/arcana.sh -m 1 | cut -d ' ' -f 2 | cut -d _ -f 2 | cut -d - -f 1)"
          rel_date="$(date "+%Y%m%d")"
          output="out/target/product/$device/*$rel_date*.zip"
          ota="out/target/product/$device/*ota*.zip"
          cd $my_dir/$rom_name
          rclone copy --drive-chunk-size 256M --stats 1s $output NFS:rom/$rom_name -P
          echo "Download link https://needforspeed.projek.workers.dev/rom/$rom_name/$(cd out/target/product/$device && ls *$rel_date*.zip)"
          rm -rf $my_dir/$rom_name/out/target/product/$device
